#enabling all the actuators endpoints
management:
  endpoints:
    web:
      exposure:
        include: "*"

#eureka config
eureka:
  client:
  service-url:
    defaultZone: http://localhost:8761/eureka
